# Generated by Django 4.2 on 2024-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shitsukan_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_count",
            field=models.IntegerField(default=8),
        ),
    ]
